### PR TITLE
Add Ability to have Encryption for ORM and ODM at the same time

### PR DESCRIPTION
**Pull request by wodka**
I use it for both entities and documents, but have not tested the update command.

### CODE REVIEW

**Comment by wodka** [comment]
Just now also fixed a bug when the entity is persisted multiple times

**Comment by westinpigott** [comment]
@wodka, Sorry for the LONG delayed response, and thanks for making these changes.  I am reviewing the PR, and I noticed a few things.
1. You added listeners on a bunch of Doctrine events.  This seems repetitive.  Why?
2. I am concerned that using both services simultaneously will cause conflicts with the default ObjectManager functionality.  I admit I have not tested this theory yet.  Thoughts?

**Comment by wodka** [comment]
Hi @westinpigott

1. I added those to decrypt the model after saving - without that you will not have access to the data after the persist
2. I'm using it for entities and documents at the same time - till now no problems appeared.

**Comment by westinpigott** [comment]
OK.  I merged it.  I am in the process of changing the way the listeners are fired for Issue #16, so those parts will change.

**Pull request merged**
